# mongodb
spring:
  data:
    mongodb:
      database: springmongodb
      host: localhost
      port: 27017

# logging
logging:
  level:
    root: warn
    com.springmvc.springmongodbweb: debug
    org.springframework.web: info
    org.springframework.data: debug
    org.hibernate: error
