spring:
  main.banner-mode: 'off'

  # mongodb
  data:
    mongodb:
      database: springmongodb
      host: localhost
      port: 27017

server:
  error:
    whitelabel.enabled: false
    include-stacktrace: always

# logging
logging:
  level:
    root: warn
    com.springmvc.springmongodbweb: debug
    org.springframework.web: info
    org.springframework.data: debug
    org.hibernate: error
